basedir = "lib/"

love.filesystem.load(basedir .. "AnAL.lua")()
love.filesystem.load(basedir .. "TEsound.lua")()

love.filesystem.load(basedir .. "lib.oop.lua")()
love.filesystem.load(basedir .. "lib.vector2.lua")()
love.filesystem.load(basedir .. "lib.vector.lua")()
love.filesystem.load(basedir .. "lib.quaternion.lua")()
love.filesystem.load(basedir .. "lib.array.lua")()
love.filesystem.load(basedir .. "lib.distance.lua")()
love.filesystem.load(basedir .. "lib.event.lua")()
love.filesystem.load(basedir .. "lib.file.lua")()
love.filesystem.load(basedir .. "lib.input.lua")()
love.filesystem.load(basedir .. "lib.job.lua")()
love.filesystem.load(basedir .. "lib.listener.lua")()
love.filesystem.load(basedir .. "lib.math.lua")()
love.filesystem.load(basedir .. "lib.profile.lua")()
love.filesystem.load(basedir .. "lib.queue.lua")()
love.filesystem.load(basedir .. "lib.string.lua")()
love.filesystem.load(basedir .. "lib.util.lua")()
love.filesystem.load(basedir .. "lib.vardump.lua")()
love.filesystem.load(basedir .. "lib.xml.lua")()
love.filesystem.load(basedir .. "lib.invokelater.lua")()
love.filesystem.load(basedir .. "lib.draw.lua")()

love.filesystem.load(basedir .. "class.objectPool.lua")()
love.filesystem.load(basedir .. "class.tiledMap.lua")()
love.filesystem.load(basedir .. "class.timer.lua")()
love.filesystem.load(basedir .. "class.grid.lua")()
love.filesystem.load(basedir .. "class.aStar.lua")()
